# Default values for chart-tp4.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

PV:
 webserver:
  name: deno-server
  size: 3Gi
  path: /data/deno-server/
  persistentVolumeReclaimPolicy: Retain
 mariadb:
  name: maria-db
  size: 10Gi
  path: /data/maria-db/
  persistentVolumeReclaimPolicy: Retain

PVC:
 webserver:
  name: webserver
  size: 1Gi
  volumeName: webserver
 mariadb:
  name: maria-db
  size: 1Gi
  volumeName: maria-db

webserver:
  volumeMount:
   name: logs
   mountPath: /srv/app/pvc
  volumes:
   name: "logs"
   claimName: "logs"
  service:
   type: NodePort
   port: 80
   name: ext-to-int-webserver
  image:
   repository: codebuds/deno-webserver
   pullPolicy: IfNotPresent
   tag: 1.5.0
  replicaCount: 3

mariadb:
  rootPassword: rootPassword
  user: user
  password: password
  volumeMount:
    name: maria-db
    mountPath: /var/lib/mysql
  volumes:
    name: maria-db
    claimName: maria-db
  service:
    name: maria-db

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80